before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - '386'
      - arm64
      - arm
    goarm:
      - '6'
      - '7'
checksum:
  name_template: 'checksums.txt'
changelog:
  use: github
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Other'
      order: 999
  filters:
    exclude:
      - typo
release:
  prerelease: auto
  mode: append
